### ISSUE TITLE
Last lodash commit publish to npm

### ISSUE THREAD

**Issue by srunicornio** [coinbase/coinbase-commerce-node#15]
Publish last commit to 'npm' please. I'm still downloading the oldest version (1.0.0) with lodash vulnerability.

**Comment by guacamoli** [comment]
Hey, sorry about the delay here. Should be getting this done early next week.

**Comment by guacamoli** [comment]
Actually, just got it done!

**Comment by Quant-Network** [comment]
This issue has resurfaced. In NPM the latest version is (1.0.1) with lodash vulnerability.
