### ISSUE TITLE
What are the possible payments statuses?

### ISSUE THREAD

**Issue by Quant-Network** [coinbase/coinbase-commerce-node#20]
Hello,

In the API docs is not specified what are the possible payment statuses and their meaning. Neither what happens when a confirmed block is rolled-back. Please would like to know about it.

Thanks.

**Comment by oa-coinbase** [comment]
@Quant-Network Hi, sorry for the delayed response. You can check the Charge Timeline section for possible payment statuses: https://commerce.coinbase.com/docs/api/#charges. I'm not sure what you mean by "when a confirmed block is rollded-back", can you clarify?

**Comment by Quant-Network** [comment]
Thanks for the update. Sure, in the unlikely event of for example bitcoin block chain forks and because of that the payment is "rolled-back" what coinbase API do in such a scenario. Thank  you

**Comment by oa-coinbase** [comment]
@Quant-Network coinbase systems are set up to handle chain re-orgs and display the correct status, it should correct itself and re-process with the correct status if your transaction was part of a re-org.

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a few months (granted, maintainers for this repo were in flux for a while). Please feel free to reopen it if you still encounter this issue with the latest stable version, thanks!
