### ISSUE TITLE
Error: No such API Key.

### ISSUE THREAD

**Issue by basit1327** [coinbase/coinbase-commerce-node#22]
I was using the old coinbase library [coinbase-node](https://github.com/coinbase/coinbase-node) and it was working fine but now i want to upgrade to this new library, i use the sample code to create checkout by this sample code (Try to create checkout via Checkout resource create method) [sample](https://github.com/coinbase/coinbase-commerce-node/blob/master/examples/resources/checkout.js) but it gives error that **No such API Key**

**Comment by basit1327** [comment]
Here is my API Key which have all the access enabled 
![API Key snapshot](https://user-images.githubusercontent.com/27570442/64759504-b60e4800-d550-11e9-9069-cd2108ea076f.PNG)

**Comment by basit1327** [comment]
`'use strict';

const APIKEY = '--------';

var coinbase = require('coinbase-commerce-node');
var Client = coinbase.Client;
var Checkout = coinbase.resources.Checkout;

Client.init(APIKEY);

var checkoutData = {
	'name': 'The Sovereign Individual',
	'description': 'Mastering the Transition to the Information Age',
	'pricing_type': 'fixed_price',
	'local_price': {
		'amount': '100.00',
		'currency': 'USD'
	},
	'requested_info': ['name', 'email']
};


setTimeout(()=>{
		Checkout.create(checkoutData, function (error, response) {
			if ( error )
				console.log('err',error);
			else {
				console.log('res',response);
			}
		});
},3000);

`

**Comment by basit1327** [comment]
i created a new account at https://commerce.coinbase.com/dashboard and setup a new api key now this is working

**Comment by joeyfrich** [comment]
I ran into this same problem.  You are using a Coinbase customer account api key but you should be using a Coinbase Commerce account api key (https://commerce.coinbase.com/).
