### ISSUE TITLE
req.on() never called in webhook

### ISSUE THREAD

**Issue by basit1327** [coinbase/coinbase-commerce-node#23]
As code provided in the example of webhook.js i created a ngrok address and send  a test request , and yes test request received but as you write a middleware for rawBody in which two events are defined 
      
       req.on('data', function (chunk) {
            console.log('step 2:');
            data += chunk;
        });
        req.on('end', function () {
            req.rawBody = data;
            next();
        });

none of the above method called , so **req.rawBody** remain undefined

**Comment by oa-coinbase** [comment]
Just tested, seems to work fine. rawBody function is a custom body parser but you can use any you'd like. Perhaps this may help https://expressjs.com/en/4x/api.html#req.body

**Comment by daminufe** [comment]
I am experiencing the same issue: 
```
const rawBody = (req, res, next) => {
    let data = '';
    req.on('data', chunk => { data += chunk; });
    req.on('end', () => {
        req.rawBody = data;
        next();
    });
};```

Then I use it:

``` 
app.use(rawBody);
```

And my `POST` is never executed - so never falls into the `req.on('end', () => ... )`
