### ISSUE TITLE
Unable to trigger AWS lambda with webhook

### ISSUE THREAD

**Issue by ioitiki** [coinbase/coinbase-commerce-node#24]
We are having an issue triggering our AWS lambda using the Coinbase commerce webhook.

What we tried:
Set up Coinbase webhook to trigger AWS lambda function with API Gateway.

What happened:
Lambda not triggered. And we received this error message:

`Hostname xxxxxx.execute-api.us-east-1.amazonaws.com resolved to a private, loopback, or otherwise reserved IP`

What should happen:
Our lambda function should execute when webhook is fired.

**Comment by oa-coinbase** [comment]
@ioitiki I am not familiar with triggering lambda, have you tried messing with cors/ privacy settings?

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a few months (granted, maintainers for this repo were in flux for a while). Please feel free to reopen it if you still encounter this issue with the latest stable version, thanks!

**Comment by neutrorebrands** [comment]
We are also facing the same issue now. Did you find any way to resolve it or still it is unresolved?

**Comment by neutrorebrands** [comment]
> We are having an issue triggering our AWS lambda using the Coinbase commerce webhook.
> 
> What we tried: Set up Coinbase webhook to trigger AWS lambda function with API Gateway.
> 
> What happened: Lambda not triggered. And we received this error message:
> 
> `Hostname xxxxxx.execute-api.us-east-1.amazonaws.com resolved to a private, loopback, or otherwise reserved IP`
> 
> What should happen: Our lambda function should execute when webhook is fired.

We are also facing the same issue now. Did you find any way to resolve it or still it is unresolved?

**Comment by olfal** [comment]
Same problem here 👀

**Comment by olfal** [comment]
Solved it by using a custom domain for my Lambda in AWS API Gateway.

**Comment by Pranav2509** [comment]
Hey! we are also facing the same issue. How did you solve it? I added a custom domain to my API Gateway, but still coinbase gives the same error. 

`Hostname xxxxxx.execute-api.us-east-1.amazonaws.com resolved to a private, loopback, or otherwise reserved IP`

Thank you for your help.
