### ISSUE TITLE
Charge resource - timeline CONFIRMED - DOC info

### ISSUE THREAD

**Issue by borodadada** [coinbase/coinbase-commerce-node#25]
in official DOC
https://commerce.coinbase.com/docs/api/#charges

Example

```
 "timeline": [
..........
    {
      "time": "2017-01-31T20:50:02Z",
      "status": "CONFIRMED"
    }, 
....................
```

 "status": "CONFIRMED"  <<<<<

BUT below writed

Charge Timeline

status | string | One of the following statuses: NEW, PENDING, COMPLETED, EXPIRED, UNRESOLVED, RESOLVED, CANCELED
-- | -- | --

COMPLETED <<<<<

I need know whats correctly?

**Comment by oa-coinbase** [comment]
Hi @borodadada sorry for the very late reply, it is COMPLETED. There was a typo in the docs and it's fixed now, thanks for pointing it out.
