### ISSUE TITLE
Charge response problem..!

### ISSUE THREAD

**Issue by Gennttii** [coinbase/coinbase-commerce-node#26]
Hi,

I am trying to make an app and I choosed coinbase commerce to receive payments.

I want users to write their amount they want to deposit, made it possible with :
`var Charge = coinbase.resources.Charge;`, but the problem is that this is considered as donation, in the end of the deposit it says thanks for the donation. 

I am not asking for donations, so I don't want it to say 

```
Donation Sent
Thank you for your donation
```

Can you remove the word donation here? Or make it possible to customize it the way I want..

Thanks in advance..

**Comment by oa-coinbase** [comment]
@Gennttii When creating a new Charge, you must set `pricing_type` to `fixed_price`, and also define the `local_price`. Otherwise it will be seen by the api as a donation.

**Comment by mworks-proj** [comment]
Are there any other parameters than fixed_price, such as recurring billing ie monthly_price, weekly_price or other?
