### ISSUE TITLE
Curl request Documentation issue

### ISSUE THREAD

**Issue by gabkk** [coinbase/coinbase-commerce-node#28]
Hi
I know it's probably not the right place to post this issue but i didn't find any other place

From your documentation page:
[https://commerce.coinbase.com/docs/api/#charges](https://commerce.coinbase.com/docs/api/#charges)

You are missing one backslash, and there is one comma which shouldn't be there

curl https://api.commerce.coinbase.com/charges \\
     -X POST \\
     -H 'Content-Type: application/json' \\
     -H "X-CC-Api-Key: <Your API Key>" \\
     -H "X-CC-Version: 2018-03-22"
     -d '{
       "name": "The Sovereign Individual",
       "description": "Mastering the Transition to the Information Age",
       "local_price": {
         "amount": "100.00",
         "currency": "USD"
       },
       "pricing_type": "fixed_price",
       "metadata": {
         "customer_id": "id_1005",
         "customer_name": "Satoshi Nakamoto"
       },
       "redirect_url": "https://charge/completed/page",
       "cancel_url": "https://charge/canceled/page",
     }'

We get an error:
`{"error":{"type":"invalid_request","message":"Malformed parameters"}}`

The correct request is 

curl https://api.commerce.coinbase.com/charges \\
-X POST \\
-H 'Content-Type: application/json' \\
-H "X-CC-Api-Key: <Your API Key>" \\
-H "X-CC-Version: 2018-03-22" \\
-d '{
  "name": "The Sovereign Individual",
  "description": "Mastering the Transition to the Information Age",
  "local_price": {
    "amount": "100.00",
    "currency": "USD"
  },
  "pricing_type": "fixed_price",
  "metadata": {
    "customer_id": "id_1005",
    "customer_name": "Satoshi Nakamoto"
  },
  "redirect_url": "https://charge/completed/page",
  "cancel_url": "https://charge/canceled/page"
}'

The response is correct

`{"data":{"addresses":{"bitcoincash" ....`

**Comment by oa-coinbase** [comment]
Thanks for the mention @gabkk this fix will be going in today.
