### ISSUE TITLE
charge payment page

### ISSUE THREAD

**Issue by 7c** [coinbase/coinbase-commerce-node#29]
Hi, we are new at coinbase, i want to use checkout api to accept one time payments via API. I can create them but i don't know what to do with these objects. Obviously i somehow need to redirect users to some checkout page hosted at coinbase right? I have been searching long time without any success, what do i do with that object after .create please?

**Comment by 7c** [comment]
obviously the missing information is https://commerce.coinbase.com/checkout/<id> - i keep it here for anybody who might need this obvious information !

**Comment by oa-coinbase** [comment]
Hi @7c have you taken a look through [the docs](https://commerce.coinbase.com/docs) and [API](https://commerce.coinbase.com/docs/api/)? Sure I can help speed it up for you- Checkout is essentially a template for Charge; you can create it via the api or from your merchant [checkouts tab](https://commerce.coinbase.com/dashboard/checkouts). You can direct your customers via full page url or embed it using the example code shown there. Checkout will not redirect customers after a payment though.

If you want to add a "redirect_url" and/ or "cancel_url", it only exists on charge through the API for now. So I recommend you calculate your checkout price, create a charge, and send them to https://commerce.coinbase.com/charge/:charge_code - it will automatically handle redirect based on what you set.

**Comment by 7c** [comment]
@oa-coinbase wow thanks for that quick response. Yes indeed i have checked the docs and read whole API. Indeed redirect_url and cancel_url are big features we really might need! I will be looking at Charge instead of Checkout then, thanks

**Comment by destroyace** [comment]
It has been two years now. When does Coinbase plan on adding redirects to checkouts?

**Comment by DevNomadAbhi** [comment]
Still coinbase doesn't redirects to checkout after authentication .

**Comment by destroyace** [comment]
For real lol, horrible support.
