### ISSUE TITLE
Coinbase Commerce Shopify

### ISSUE THREAD

**Issue by jstefanop** [coinbase/coinbase-commerce-node#4]
Hey who is responsible for the Shopify integration of coinbase commerce? Having some issues with failed payments due to underpayments or late payments.

**Comment by guacamoli** [comment]
Not related to this project.

**Comment by Lexi2066** [comment]
I am having the same problem, can I ask if you fixed the issue how did you do that. It is very frustrating when you check out your store and there is failed payment after failed payment from coinbase. Thank you
