### ISSUE TITLE
Create Checkout - logo_url

### ISSUE THREAD

**Issue by davecarlson** [coinbase/coinbase-commerce-node#49]
Currently, you can upload images via the API to create a checkout, but the hosted pages do not show the image, due to a cross origin error.

You can upload images via the website interface, but this is very sloe for large catalogues.

Is there a way to get the images backed onto your CDN to allow them to be visible ?

**Comment by davecarlson** [comment]
"Refused to load the image 'https://assets.MYSITE.com/image-4.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data: https://exceptions.coinbase.com/js https://res.cloudinary.com https://www.google-analytics.com/ https://images.coinbase.com"."

**Comment by jhonatan-maza** [comment]
Se solucionó el problema because it violates the following Content Security Policy directive: "img-src 'self' data: https://exceptions.coinbase.com/js https://res.cloudinary.com/ https://www.google-analytics.com/ https://images.coinbase.com/"."
